### PR TITLE
Remove toolbar

### PR DESCRIPTION
**Pull request by yihyunjoon**

### CODE REVIEW

**Comment by yihyunjoon** [comment]
screen shot 2016-09-30 at 18 42 24

**Review by aweekj — COMMENTED** [review]
I think the laster ui version is more intuitive design.

**Comment by aweekj** [comment]
I think the lastest UI version is more intuitive design!

**Comment by yihyunjoon** [comment]
Wait for next commit :p

**Review by yihyunjoon — COMMENTED** [review]
Lorem ipsum

**Review by yihyunjoon — COMMENTED** [review]
Lorem ipsum 2

**Pull request closed without merging**
